version: '3.3'
services:
  web:
    build:
      context: ./app
    image: kiranrepository2023/flaskapp:latest
    ports:
      - "8010:8010"
    volumes:
      - ./app:/app
    environment:
      FLASK_ENV: development

